// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO3W5qaThBbvEXFZd-rQlmqMV5WgqbODY',
    appId: '1:701435614195:web:746024005d579a9aa2f886',
    messagingSenderId: '701435614195',
    projectId: 'lab4-c6279',
    authDomain: 'lab4-c6279.firebaseapp.com',
    storageBucket: 'lab4-c6279.firebasestorage.app',
    measurementId: 'G-KVEWLZ7C8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRJyrEGj57fzbVL0d-mfN2CdXbcaG7Ijs',
    appId: '1:701435614195:android:2ff7122de64eb8dba2f886',
    messagingSenderId: '701435614195',
    projectId: 'lab4-c6279',
    storageBucket: 'lab4-c6279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfg84T0tKn6l2Y2nFtTwnPudlImBgiOZo',
    appId: '1:701435614195:ios:becd3b7a7c9bfc67a2f886',
    messagingSenderId: '701435614195',
    projectId: 'lab4-c6279',
    storageBucket: 'lab4-c6279.firebasestorage.app',
    iosBundleId: 'com.lab4.lab4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfg84T0tKn6l2Y2nFtTwnPudlImBgiOZo',
    appId: '1:701435614195:ios:becd3b7a7c9bfc67a2f886',
    messagingSenderId: '701435614195',
    projectId: 'lab4-c6279',
    storageBucket: 'lab4-c6279.firebasestorage.app',
    iosBundleId: 'com.lab4.lab4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO3W5qaThBbvEXFZd-rQlmqMV5WgqbODY',
    appId: '1:701435614195:web:f5a4683eb12bd3e9a2f886',
    messagingSenderId: '701435614195',
    projectId: 'lab4-c6279',
    authDomain: 'lab4-c6279.firebaseapp.com',
    storageBucket: 'lab4-c6279.firebasestorage.app',
    measurementId: 'G-8DPKKCMJCS',
  );
}
